### ISSUE TITLE
 DEBUG command not allowed in redis 7

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabsModules/redisbench-admin#288]
```
CRITICAL:root:<class 'redis.exceptions.ResponseError'>
2022-02-16 22:37:39,007 CRITICAL <class 'redis.exceptions.ResponseError'>
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/redisbench_admin/run_remote/run_remote.py", line 292, in run_remote_command_logic
    ) = remote_db_spin(
  File "/usr/local/lib/python3.9/dist-packages/redisbench_admin/run_remote/remote_db.py", line 252, in remote_db_spin
    debug_reload_rdb(dataset_load_timeout_secs, redis_conns)
  File "/usr/local/lib/python3.9/dist-packages/redisbench_admin/run/cluster.py", line 77, in debug_reload_rdb
    conn.execute_command("DEBUG RELOAD NOSAVE")
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
------------------------------------------------------------
```

**Comment by filipecosta90** [comment]
Fixed by #361
